http:
  addr: ":8081"
  payment_timeout: 500ms

redis:
  addr: "localhost:6379"
  prefix: "idem:checkout:"
  db: 0

database:
  host: "localhost"
  port: 5432
  name: "app"

kafka:
  brokers: ["localhost:19092"]
  batch_size: 25
  batch_timeout: 15ms
  payments_topic: "payments.initiated.v1"
  client_id: "checkout"

outbox:
  poll_interval: 200ms
  poll_timeout: 2s
  reset_events_interval: 1s
  reset_events_timeout: 1s
  batch_size: 100
  max_parallel: 25