http:
  addr: ":8081"
  payment_timeout: 500ms

redis:
  addr: "localhost:6379"
  prefix: "idem:checkout:"
  db: 0

database:
  host: "localhost"
  port: 5432
  name: "app"

kafka:
  brokers: "localhost:19092"
  payments_topic: "payments.initiated.v1"
  client_id: "checkout"

outbox:
  enabled: true
  poll_interval_ms: 200
  batch_size: 100
  backoff_base_ms: 200
  backoff_max_ms: 30000